default: &default
  adapter: mysql2
  encoding: utf8
  username: vagrant
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dashboard

test:
  <<: *default
  database: dashboard_testing
